### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by projecttiles** [skokenes/d3-lasso#3]
Hey skokenes,

I spent some of today fiddling with the new d3v4 + lasso code. I basically made some minor syntax adjustments and it works fluidly on my desktop. No more flickers/ unselected points in lasso!

However, it appears that the lasso (or perhaps just lasso_end) isn't working on mobile. I tested it in chrome on my Android phone, and my friend tested it using safari on her iPhone.
The example in question is: http://bl.ocks.org/skokenes/a85800be6d89c76c1ca98493ae777572

To decribe in better detail what happens:

- on my phone, bl.ocks doesn't load the graph at all
- on her phone, she's able to start and draw the lasso, but after the lasso disappears, the points remain unselected

Sorry to post this so late, I only just started playing with the new code yesterday.
Cheers,

-Ben

**Comment by projecttiles** [comment]
Here's a gif of what I'm referring to. Note the lack of a dotted line connecting the final drag-point to the initial drag-point. The lasso_end function also spouts a TypeError when trying to pull the color from the data, indicating that it's not able to access the data points in the lasso. This only occurs on mobile, with the exception of windows phones. 
![mobilelassoerror](https://cloud.githubusercontent.com/assets/8890017/19080141/19bbe4dc-8a24-11e6-99cf-cb6f2a26911a.gif)

**Comment by skokenes** [comment]
Fixed in v0.0.5
