### ISSUE TITLE
Ability to draw a path automatically based on the given selected node info

### ISSUE THREAD

**Issue by venki227** [skokenes/d3-lasso#8]
Use case: I created a scatter plot and implemented a lasso selection on it. Let's say I have a nodes with names as [1, 2, 3, .....10]. Now I am able to select the nodes 2,3,7,10 using lasso and stored this values in a array. Now I want to invert this operation, like when I give a array of nodes is it possible to draw a path around these given nodes? Please see below image 
<img width="1081" alt="Screen Shot 2019-07-25 at 1 21 15 PM" src="https://user-images.githubusercontent.com/15823506/61905957-2567a400-aedf-11e9-8bf1-a61a42fb63ae.png">

**Comment by venki227** [comment]
@skokenes Please let me know. Is this possible?

**Comment by skokenes** [comment]
In this plugin, it is not possible but more generally you should be able to accomplish this in your visualization using d3 and a hull algorithm like the following lib: https://github.com/AndriiHeonia/hull
